# Generated by Django 4.2 on 2023-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='phtoto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/', verbose_name='Фото'),
        ),
    ]
