# Generated by Django 4.2 on 2023-04-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_productimage_phtoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='phtoto',
            new_name='photo',
        ),
    ]
